spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/worldishes
    username: dia
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
amazon:
  aws:
    accessKey: ${WORLDISHES_AWS_ACCESS_KEY}
    secretKey: ${WORLDISHES_AWS_SECRET_KEY}
    region: ${WORLDISHES_AWS_REGION}

aws:
  s3:
    bucket: worldishes-images-bucket

jwt:
  secret: ${WORLDISHES_JWT_SECRET}