spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/worldishes
    username: dia
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
amazon:
  aws:
    accessKey: AccessKey
    secretKey: SectretKey
    region: Region

aws:
  s3:
    bucket: BucketName